### ISSUE TITLE
Conectar ao banco de homologação via VPN

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-api#12]
Ao rodar o salic-api local ele deve mostrar os dados do ambiente de produção.

**Comment by edsonma** [comment]
https://github.com/dlenski/openconnect

https://hub.docker.com/r/softplan/openconnect-globalprotect/

**Comment by edsonma** [comment]
Container Source
https://github.com/edsonma/docker-openconnect-globalprotect

DockerHub Image
https://hub.docker.com/r/edsonma/openconnect-globalprotect/
