### ISSUE TITLE
estudo e pesquisa aplicada ao metabase (BI)

### ISSUE THREAD

**Issue by marcosronaldo** [lappis-unb/salic-api#30]
Issue cancelada!

**Comment by joenio** [comment]
adicilnalmente ao estudo sobre ao metabase peço que pesquisem também sistemas de visualização de dados com bons dashboards para sugerir ao @peterlima e @rodmaia2099 como referências para o trabalho que será desenvolvido com o versalic, será utilizado como benchmark, é necessário apenas sugerir alguns nomes de sistemas, idealmente fornecer algum material para que o @peterlima e @rodmaia2099 possam avaliar, pode ser um link para uma demo dos sistemas pesquisados por exemplo.

**Comment by joenio** [comment]
como ficou encaminhada essa atividade?
