### ISSUE TITLE
Refatorar e testar módulo de Fornecedor

### ISSUE THREAD

**Issue by navarrovmn** [lappis-unb/salic-api#7]

**Comment by LucianoPC** [comment]
A parte do Fornecedor está funcionando, e os testes estão funcionando.
Falta arrumar a parte de Produtos do Fornecedor.

Para arrumar a parte dos Produtos tem que arrumar a classe ProductQuery que está em [salic_api/resources/fornecedor/models.py - linha 106]

Ao ir arrumando a classe ProductQuery deve ir descomentando os campos da constante PRODUTOS_RESPONSE que está em [tests/examples.py - linha 178]

Também falta atualizar o id do fornecedor na url de produtos, que no teste que está:
url = '/v1/fornecedores/1/produtos'
porem deve ficar
url = '/v1/fornecedores/30313233343536373839616263646566e0797636/produtos'
