### ISSUE TITLE
Colocar o salic-api em homologação e produção no MinC

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-api#83]
Remover a condição no arquivo projeto_detail linha 125

**Comment by joenio** [comment]
Acabei de conversar com o Pedro Philipe Oliveira (@Pedroeoq -AT- Telegram) (MinC / Equipe Salic) e ele informou que no momento está dependendo de articular internamente a liberação dele para poder dedicar mais tempo a API e assim poder dar o suporte que nós Lappis precisamos para fazer o deploy da nova API em produção na infra-estrutura do MinC.

Conversei também com o Decko para iniciar essa articulação para liberar o Pedro, estamos conversando sobre isso e em breve teremos algum encaminhamento, agendei um momento para conversar com o Decko em detalhes sobre isso.

**Comment by joenio** [comment]
fechando issue para efeitos de organização das sprints, continuar na issue #86.
