### ISSUE TITLE
Problemas na homologação da API

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-api#92]
Fiz alguns testes preliminares com a nova API e identifiquei alguns problemas. Passo a rota em produção e na minha máquina em testes. Acho que podemos também atualizar o hmg.api.salic, que está fora e estava em http://hmg.app.api.salic.cultura.gov.br/.

## Projetos

# "Ver projeto" :heavy_check_mark: 

Não consigo visualizar informações detalhadas do "projeto". Urls:

http://api.salic.cultura.gov.br/v1/projetos/090055/   - OK
http://10.1.20.145:88/v1/projetos/090055/

# Filtragem por área e segmento não retorna resultados. 

http://api.salic.cultura.gov.br//v1/projetos/?limit=12&offset=0&sort=PRONAC:desc&area=1
http://10.1.20.145:88/v1/incentivadores/?limit=12&offset=0&PRONAC=151615&sort=total_doado:desc

# Filtragem por data de início e fim não retorna resultados:

http://api.salic.cultura.gov.br/v1/projetos/?limit=12&offset=0&UF=AM&sort=PRONAC:desc&data_inicio_min=2008-10-6&data_termino_max=2009-10-15
http://10.1.20.145:88/v1/projetos/?limit=12&offset=0&UF=AM&sort=PRONAC:desc&data_inicio_min=2008-10-6&data_termino_max=2009-10-15

## Propostas

# Ver proponentes

Não consigo realizar nenhum tipo de busca relacionada a proponentes. Urls:

http://api.salic.cultura.gov.br/v1/proponentes/?limit=12&offset=0&nome=projeto&sort=total_captado:desc   - OK
http://10.1.20.145:88/v1/proponentes/?limit=12&offset=0&nome=projeto&sort=total_captado:desc

# Não consigo filtrar propostas por data

http://api.salic.cultura.gov.br/v1/propostas/?limit=12&offset=0&data_inicio_min=2010-9-13&data_termino_max=2012-10-16
http://10.1.20.145:88/v1/propostas/?limit=12&offset=0&data_inicio_min=2010-9-13&data_termino_max=2012-10-16

## Incentivadores:

Não consigo buscar informações por número de PRONAC

http://10.1.20.145:88/v1/incentivadores/?limit=12&offset=0&PRONAC=151615&sort=total_doado:desc

## Fornecedores:

# Não consigo filtrar por CPF/CNPJ. Quebrado também em prod.

http://api.salic.cultura.gov.br/v1/fornecedores/?limit=12&offset=0&cgccpf=22487089806
http://10.1.20.145:88/v1/fornecedores/?limit=12&offset=0&cgccpf=22487089806

# Não consigo filtrar por PRONAC. Quebrado também em prod.

http://api.salic.cultura.gov.br/v1/fornecedores/?limit=12&offset=0&PRONAC=131250

Não exauri completamente os testes, mas acredito que é necessário fazer uma bateria de testes criteriosa.

**Comment by joenio** [comment]
separei essa issue em issues menores para facilitar a gestão.

**Comment by joenio** [comment]
todos os bugs relatados foram resolvidos.
